What You're Aiming For

Name : Transforming COVID19 data

 

Description : In this checkpoint, we’re going to transform the data in the covid19 file.


Instructions

Let us take the example of the previous super skill after connecting to the COVID-19 file:   ( CSV file ➡️ HERE )

1. Change the name of the dataRep column into Date.

2. Duplicate the Date column in order to be able to slip it. 

3. Split one of the Date columns based on the “/” seperator in order to extract the day, month and year columns that will be very useful for a detailed analysis.

4. Verify that the different field types are correct (check entirely the days, months, years..)

5. Replace the null values with 0 in order to be able to make aggregations later, during the visualization.

6. Rename the columns with meaningful names.

 

PS: here is the Link to the dataset (provided by Microsoft  power bi extension),  CSV ➡️ HERE

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("covid_tracking.csv")

df

,date,state,positive,negative,pending,hospitalized_currently,hospitalized_cumulative,in_icu_currently,in_icu_cumulative,on_ventilator_currently,...,fips,death_increase,hospitalized_increase,negative_increase,positive_increase,total_test_results_increase,fips_code,iso_subdivision,load_time,iso_country
0,2021-03-07,AK,56886.0,NaN,NaN,33.0,1293.0,NaN,NaN,2.0,...,2,0,0,0,0.0,0,2,US-AK,2024-12-28 00:04:26,US
1,2021-03-07,AL,499819.0,1931711.0,NaN,494.0,45976.0,NaN,2676.0,NaN,...,1,-1,0,2087,408.0,2347,1,US-AL,2024-12-28 00:04:26,US
2,2021-03-07,AR,324818.0,2480716.0,NaN,335.0,14926.0,141.0,NaN,65.0,...,5,22,11,3267,165.0,3380,5,US-AR,2024-12-28 00:04:26,US
3,2021-03-07,AS,0.0,2140.0,NaN,NaN,NaN,NaN,NaN,NaN,...,60,0,0,0,0.0,0,60,US-AS,2024-12-28 00:04:26,US
4,2021-03-07,AZ,826454.0,3073010.0,NaN,963.0,57907.0,273.0,NaN,143.0,...,4,5,44,13678,1335.0,45110,4,US-AZ,2024-12-28 00:04:26,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22256,2020-01-17,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,0,0,0,0.0,0,53,US-WA,2024-12-28 00:04:26,US
22257,2020-01-16,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,0,0,0,0.0,0,53,US-WA,2024-12-28 00:04:26,US
22258,2020-01-15,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,0,0,0,0.0,0,53,US-WA,2024-12-28 00:04:26,US
22259,2020-01-14,WA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,0,0,0,0.0,0,53,US-WA,2024-12-28 00:04:26,US
22260,2020-01-13,WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,0,0,0,0.0,0,53,US-WA,2024-12-28 00:04:26,US

In [4]:
# Rename the column
df.rename(columns={'dataRep': 'Date'}, inplace=True)

In [3]:
# Duplicate the Date column
df['Date_duplicated'] = df['date']

In [ ]:
# Split the Date column into Day, Month, and Year
df[['Day', 'Month', 'Year']] = df['date'].str.split('/', expand=True)

In [ ]:
# Convert Day, Month, and Year to appropriate data types
df['day'] = pd.to_numeric(df['day'], errors='coerce')
df[';onth'] = pd.to_numeric(df['month'], errors='coerce')
df['year'] = pd.to_numeric(df['year'], errors='coerce')

In [8]:
# Replace NaN values with 0
df.fillna(0, inplace=True)

In [9]:
# Rename columns with more meaningful names
df.rename(columns={
    'Day': 'Day_of_Month',
    'Month': 'Month_of_Year',
    'Year': 'Year_of_Observation',
    'date': 'Original_Date',
    'Date_duplicated': 'Duplicated_Date'
}, inplace=True)

df